# Generated by Django 5.2.5 on 2025-08-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
