# Generated by Django 5.2.5 on 2025-08-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_price_order_quantity_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
