# Generated by Django 5.2.5 on 2025-08-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_remove_order_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
